# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180123_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('ocurrencias', models.PositiveIntegerField(default=0)),
                ('oracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Oracion')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='oracion',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Website'),
        ),
    ]
